site_name: Hitachi Visualization Suite
theme:
  name: material
  favicon: ..overrides/images/favicon.png
  logo: ..overrides/assets/images/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    - toc.integrate
    - navigation.expand
    - navigation.footer
  extra_css:
     - assets/stylesheets/extra.css
     - assets/stylesheets/bootstrap.min.css  

  extra_javascript:
    - assets/javascripts/bootstrap.min.js   
  language: en
  theme:
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    
  
  plugins: 
  - pdf-export:
      combined: false