site_name: Hitachi Smartspaces
site_url: https://www.hvsmartspaces.com
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    - toc.integrate
    - navigation.expand
    - navigation.footer
  
  language: en
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny  
        name: Dark mode
      primary: green
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night  
        name: Light mode
      primary: blue
      accent: deep orange
