site_name: Hitachi Smartspaces
theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    - toc.integrate
    - navigation.expand
    - navigation.footer
      - copyright: © 2025 Hitachi Vantara, LLC. All rights reserved.
  language: en
  palette:
    - scheme: default
    - toggle:
    - icon: material/toggle-switch-off-outline  
    - name: Switch to dark mode
    - primary: teal
    - accent: purple
    - scheme: slate
    - toggle:
    -  icon: material/toggle-switch
    - name: Switch to light mode
    - primary: teal
    - accent: lime
