title: My Sample Website

sections:
  - title: Introduction
    pages:
      - title: Welcome
      - title: About Me
  - title: Technical Topics
    pages:
      - title: MkDocs Basics
      - title: Markdown Essentials
      - title: GitHub Integration
  - title: Contact
    pages:
      - title: Contact Form

plugins:
  - mkdocs-yaml:
      file: index.yaml